' Gambas module file

Private iIDProyecto As Integer
Private Contenido As Result

Public Sub ObtenerIdNuevoArticulo()

  Dim Idn As Integer
  Dim MaxId As Variant

  MaxId = m_OnOff_y_Red.meConn.Exec("SELECT MAX(id) FROM articulos LIMIT 1")

  If MaxId["MAX(id)"] = Null Then
    Idn = 0
  Else
    Idn = CInt(MaxId["MAX(id)"]) + 1
  Endif

  FMain.idArticulo.Text = Idn
  FMain.idProyectoArticulo.Text = FMain.idProyecto.Text

End

Public Sub GuardarArticuloPrimeraVez()

  Contenido = m_OnOff_y_Red.meConn.Create("articulos", "id=" & FMain.idArticulo.Text)

  Contenido!id_proyecto = CInt(FMain.idProyectoArticulo.Text)' tomo el valor del id del proyecto
  Contenido!txtArticuloTitulo = FMain.txtArticuloTitulo.Text
  Contenido!txtArticuloTituloEn = FMain.txtArticuloTituloEn.Text
  Contenido!txtArticuloTituloCorto = FMain.txtArticuloTituloCorto.Text
  Contenido!txtArticuloTituloCortoEn = FMain.txtArticuloTituloCortoEn.Text
  Contenido!txtArticuloSubtitulo = FMain.txtArticuloSubtitulo.Text
  Contenido!txtArticuloSubtituloEn = FMain.txtArticuloSubtituloEn.Text

  Contenido.Update
  m_OnOff_y_Red.meConn.Commit()
  RefrescarTableViewArticulos()
  Message.Info("Cambios guardados correctamente.")

Catch
  Message.Error("Error al guardar cambios: " & Error.Text)

End

Public Sub GuardarCambiosArticulo()

  Contenido = m_OnOff_y_Red.meConn.Edit("articulos", "id=" & FMain.idArticulo.Text)

  If Not Contenido.Available Then
    Message.Error("No se encontró el artículo para editar.")
    Return
  Endif

  Contenido!txtArticuloTitulo = FMain.txtArticuloTitulo.Text
  Contenido!txtArticuloTituloEn = FMain.txtArticuloTituloEn.Text
  Contenido!txtArticuloTituloCorto = FMain.txtArticuloTituloCorto.Text
  Contenido!txtArticuloTituloCortoEn = FMain.txtArticuloTituloCortoEn.Text
  Contenido!txtArticuloSubtitulo = FMain.txtArticuloSubtitulo.Text
  Contenido!txtArticuloSubtituloEn = FMain.txtArticuloSubtituloEn.Text

  Contenido.Update
  m_OnOff_y_Red.meConn.Commit()
  RefrescarTableViewArticulos()
  Message.Info("Cambios guardados correctamente.")

Catch
  Message.Error("Error al guardar cambios: " & Error.Text)

End

Public Sub MostrarArticulosEnTableViewArticulos(iRow As Integer)

  With FMain
    .idArticulo.Text = .TableViewArticulos[iRow, 0].Text
    .idProyectoArticulo.Text = .TableViewArticulos[iRow, 1].Text
    .txtArticuloTitulo.Text = .TableViewArticulos[iRow, 2].Text
    .txtArticuloTituloEn.Text = .TableViewArticulos[iRow, 3].Text
    .txtArticuloTituloCorto.Text = .TableViewArticulos[iRow, 4].Text
    .txtArticuloTituloCortoEn.Text = .TableViewArticulos[iRow, 5].Text
    .txtArticuloSubtitulo.Text = .TableViewArticulos[iRow, 6].Text
    .txtArticuloSubtituloEn.Text = .TableViewArticulos[iRow, 7].Text
  End With

End

Public Sub ConfigurarTableViewArticulos(grid As GridView)

  With grid
    .Header = True
    .Grid = True
    .Columns.Count = 50

    ' Configuración de columnas
    For i As Integer = 0 To 50
      Select Case i
        Case 0
          .Columns[i].Title = "Id"
          .Columns[i].Width = 0
        Case 1
          .Columns[i].Title = "id_proyecto"
          .Columns[i].Width = 0
        Case 2
          .Columns[i].Title = "Título"
          .Columns[i].Width = 900
      End Select
    Next
  End With

End

Public Sub RefrescarTableViewArticulos()

  FMain.TableViewArticulos.Clear
  Contenido = m_OnOff_y_Red.meConn.Exec("SELECT * FROM articulos")'
  FMain.TableViewArticulos.Rows.Count = Contenido.Count

End
