' Gambas module file

Private Contenido As Result
Private ArticulosIDs As Collection

Public Sub ObtenerIdNuevoAutor()

  Dim Idn As Integer
  Dim MaxId As Variant

  MaxId = m_OnOff_y_Red.meConn.Exec("SELECT MAX(id) FROM autores LIMIT 1")

  If MaxId["MAX(id)"] = Null Then
    Idn = 0
  Else
    Idn = CInt(MaxId["MAX(id)"]) + 1
  Endif

  FMain.idAutor.Text = Idn

End

Public Sub RefrescarTableViewArticulos()

  FMain.gbMetadatosAutores.Clear
  Contenido = m_OnOff_y_Red.meConn.Exec("SELECT * FROM autores")'
  FMain.gbMetadatosAutores.Rows.Count = Contenido.Count

End

Public Sub LlenarComboBoxArticulos()

  Dim rConsulta As Result
  Dim sSQL As String

  FMain.ComboBoxArticuloAsociado.Clear
  ArticulosIDs = New Collection

  rConsulta = m_OnOff_y_Red.meConn.Exec("SELECT id, txtArticuloTitulo FROM articulos WHERE id_revistas = &1", FMain.idMetadatoRevista.Text)

  If rConsulta.Available Then
    Repeat
      Dim titulo As String = rConsulta["txtArticuloTitulo"]
      Dim id As Integer = rConsulta["id"]

      FMain.ComboBoxArticuloAsociado.Add(titulo)
      ArticulosIDs.Add(id, titulo)

      rConsulta.MoveNext()
    Until rConsulta.Available = False
  Else
    Message.Warning("No hay artículos para mostrar.")
  Endif

Catch
  Message.Error("Error al cargar artículos: " & Error.Text)

End

Public Sub ComboBoxArticuloAsociado()

  Dim tituloSeleccionado As String = FMain.ComboBoxArticuloAsociado.Text

  If ArticulosIDs.Exist(tituloSeleccionado) Then
    FMain.idArticuloAutor.Text = ArticulosIDs[tituloSeleccionado]
  Endif

End
