' Gambas module file

Private NombreProyecto As String = File.BaseName(FMain.txtProyecto.Text)
Private RutaProyecto As String = File.Dir(FMain.txtProyecto.Text)

'exportamos el archivo bibtex
Public Sub ExportarBibTeX()

  Dim s As String
  Dim f As ResultField
  Dim aFields As New String[]
  Dim i As Integer
  Dim w As Integer
  Dim tab As String

  Dim sResultado As Result
  Dim filtrarBib As String

  'me aseguro de que la búsqueda se encuentre entre comas
  filtrarBib = "select * from bibtex where id_revista = " & FMain.idMetadatoRevista.Text
  sResultado = m_OnOff_y_Red.meConn.Exec(filtrarBib)

  aFields.Clear
  For Each f In sResultado.Fields
    aFields.Add(f.Name)
    If Len(f.Name) > w Then
      w = Len(f.Name)
    Endif
  Next

  s = "" ' Inicializa la cadena vacía

  While sResultado.Available
    s &= "\n@" & sResultado["cmbTipoDeEntrada"] & "{" & sResultado[aFields[5]] & ",\n"
    For i = 6 To aFields.Max
      tab = ""
      If Len(aFields[i]) / i < w Then
        tab = String(w - Len(aFields[i]), " ")
      Endif
      If Not IsNull(sResultado[aFields[i]]) And Len(sResultado[aFields[i]]) > 0 Then
        s &= aFields[i] & tab & " = {" & sResultado[aFields[i]] & "},\n"
      Endif
    Next
    s &= "}"
    sResultado.MoveNext
  Wend

  ' Realizar los reemplazos
  s = Replace(s, ",}", "}")
  s = Replace(s, "txtAuthor", "author ")
  s = Replace(s, "txtEditor", "editor ")
  s = Replace(s, "txtTitle", "title ")
  s = Replace(s, "txtNameAddOn", "nameaddon ")
  s = Replace(s, "txtBookAuthor", "bookauthor ")
  s = Replace(s, "txtEditorA", "x ")
  s = Replace(s, "txtEditorB", "x ")
  s = Replace(s, "txtEditorC", "x ")
  s = Replace(s, "txtAfterword", "afterword ")
  s = Replace(s, "txtForeword", "foreword ")
  s = Replace(s, "txtCommentator", "commentator ")
  s = Replace(s, "txtIntroduction", "introduction ")
  s = Replace(s, "txtTranslator", "translator ")
  s = Replace(s, "txtAnnotator", "annotator ")
  s = Replace(s, "txtHolder", "holder ")
  s = Replace(s, "txtGender", "gender ")
  s = Replace(s, "txtShortAuthor", "shortauthor ")
  s = Replace(s, "cmbEditorType", "x ")
  s = Replace(s, "cmbEditorTypeA", "x ")
  s = Replace(s, "cmbEditorTypeB", "x ")
  s = Replace(s, "cmbEditorTypeC", "x ")
  s = Replace(s, "txtTitleAddOn", "titleaddon ")
  s = Replace(s, "txtSubTitle", "subtitle ")
  s = Replace(s, "txtSeries", "series ")
  s = Replace(s, "txtBookTitle", "booktitle ")
  s = Replace(s, "txtBookTitleAddOn", "booktitleaddon ")
  s = Replace(s, "txtMainTitle", "maintitle ")
  s = Replace(s, "txtMainTitleAddOn", "maintitleaddon ")
  s = Replace(s, "txtJournalTitle", "journaltitle ")
  s = Replace(s, "txtJournalTitleAddOn", "journaltitleaddon ")
  s = Replace(s, "txtIssueTitle", "issuetitle ")
  s = Replace(s, "txtIssueTitleAddOn", "issuetitleaddon ")

  Dim fecha As String

  fecha = Format(Date(), "dd/mm/yyyy")

  s &= "\n\n@Comment{generado con gbadocmagazine; databaseType:biblatex; fecha de creación: " & fecha & ";}"

  Dim outputFile As String
  outputFile = RutaProyecto & "/files/" & NombreProyecto & ".bib"
  File.Save(outputFile, s)

End
