' Gambas module file

Private ContenidoGlo As Result

Public Sub ConfigurarViewGridGlosarioTotal(grid As GridView)

  With grid
    .Header = True
    .Grid = True
    .Columns.Count = 11

    ' Configuración de columnas
    For i As Integer = 0 To 10
      Select Case i
        Case 0
          .Columns[i].Title = "Id"
          .Columns[i].Width = 0
        Case 2
          .Columns[i].Title = "Clave"
          .Columns[i].Width = 200
        Case 3
          .Columns[i].Title = "Tipo"
          .Columns[i].Width = 100
        Case 4
          .Columns[i].Title = "Nombre"
          .Columns[i].Width = 100
        Case 7
          .Columns[i].Title = "Primera vez"
          .Columns[i].Width = 800
        Case Else
          .Columns[i].Title = ""
          .Columns[i].Width = 0
      End Select
    Next
  End With

End
