' Gambas module file

Private ContenidoMeta As Result
Private id_proyecto As Integer

Public Function ObtenerDescripcionTipo(valor As Integer) As String

  Select Case valor
    Case m_Constantes.TIPO_REVISTA_MD
      Return "Revista (Markdown)"
    Case m_Constantes.TIPO_LIBRO_MD
      Return "Libro (Markdown)"
    Case m_Constantes.TIPO_LIBRO_LATEX
      Return "Libro (LaTeX)"
    Case Else
      Return "Tipo desconocido"
  End Select

End

Public Function CargarMetadatosDelProyecto() As Boolean

  Dim sSQL As String

  ' Buscar en tabla metadatos
  sSQL = "SELECT * FROM metadatos WHERE id_proyecto = &1"
  ContenidoMeta = m_ConexionBD.mConn.Exec(sSQL, FMain.id_proyecto.Value)

  ' If Contenido.Available Then
  '   ' Asignación directa (si usas VARCHAR NOT NULL DEFAULT '')
  '   With FMain
  '     .txtNombreRevista.Text = Contenido["nombre"]
  '     .txtImagenTapita.Text = Contenido["imagen_tapita"]
  '     .txtRevistaTitulo.Text = Contenido["titulo"]
  '     .txtRevistaAbreviatura.Text = Contenido["abreviatura"]
  '     .txtRevistaDOIPrefix.Text = Contenido["doi_prefix"]
  '     .txtRevistaISSN.Text = Contenido["issn"]
  '     .txtRevistaVolumen.Text = Contenido["volumen"]
  '     .txtRevistaNumero.Text = Contenido["numero"]
  '     .txtRevistaAnio.Text = Contenido["anio"]
  '     .txtRevistaMes.Text = Contenido["mes"]
  '     .txtRevistaEditor.Text = Contenido["editor"]
  '     .txtRevistaEditorial.Text = Contenido["editorial"]
  '     .txtRevistaPais.Text = Contenido["pais"]
  '     .txtRevistaIdioma.Text = Contenido["idioma"]
  '     .txtRevistaFrecuencia.Text = Contenido["frecuencia"]
  '     .txtRevistaURL.Text = Contenido["url"]
  '     .txtRevistaEmail.Text = Contenido["email"]
  '     ' ... continúa con los demás
  '
  '     ' Para ComboBox
  '     If Not IsNull(Contenido["autoria_libro_index"]) Then
  '       .cmbAutoriaLibro.Index = Contenido["autoria_libro_index"]
  '     Endif
  '
  '     .txtGhpFooter.Text = Contenido["ghp_footer"]
  '   End With
  '
  '   Return True
  ' Else
  '   m_Sonido.sonar("Warning")
  '   Message.Warning("No se encontraron metadatos para este proyecto.")
  '   Return False
  ' Endif

Catch
  m_Sonido.sonar("Error")
  Message.Error("Error al cargar metadatos: " & Error.Text)
  Return False

End

' Public Function CargarMetadatosDelProyecto()
'
'   Dim sSQL As String
'
'   ' Usar el nombre completo del archivo (con extensión)
'   sSQL = "SELECT * FROM proyectos WHERE id_proyecto = &1"
'   ' Contenido es una variable global de este formulario
'   Contenido = m_ConexionBD.mConn.Exec(sSQL, FMain.id_proyecto.Text) 'id_proyecto es un valuebox, va text?
'
'   If Contenido.Available Then
'     ' Cargar datos del proyecto existente
'     id_proyecto = Contenido["id"]
'
'     ' Asignar valores a los controles con verificación de NULL
'     FMain.id_proyecto.Text = Contenido["id"]
'     FMain.txtNombreRevista.Text = IIf(IsNull(Contenido["nombre"]), "", CStr(Contenido["nombre"]))
'     FMain.txtImagenTapita.Text = IIf(IsNull(Contenido["txtImagenTapita"]), "", CStr(Contenido["txtImagenTapita"]))
'     FMain.txtRevistaTitulo.Text = IIf(IsNull(Contenido["txtRevistaTitulo"]), "", CStr(Contenido["txtRevistaTitulo"]))
'     FMain.txtRevistaAbreviatura.Text = IIf(IsNull(Contenido["txtRevistaAbreviatura"]), "", CStr(Contenido["txtRevistaAbreviatura"]))
'     FMain.txtRevistaDOIPrefix.Text = IIf(IsNull(Contenido["txtRevistaDOIPrefix"]), "", CStr(Contenido["txtRevistaDOIPrefix"]))
'     FMain.txtRevistaISSN.Text = IIf(IsNull(Contenido["txtRevistaISSN"]), "", CStr(Contenido["txtRevistaISSN"]))
'     FMain.txtRevistaVolumen.Text = IIf(IsNull(Contenido["txtRevistaVolumen"]), "", CStr(Contenido["txtRevistaVolumen"]))
'     FMain.txtRevistaNumero.Text = IIf(IsNull(Contenido["txtRevistaNumero"]), "", CStr(Contenido["txtRevistaNumero"]))
'     FMain.txtRevistaAnio.Text = IIf(IsNull(Contenido["txtRevistaAnio"]), "", CStr(Contenido["txtRevistaAnio"]))
'     FMain.txtRevistaMes.Text = IIf(IsNull(Contenido["txtRevistaMes"]), "", CStr(Contenido["txtRevistaMes"]))
'     FMain.txtRevistaEditor.Text = IIf(IsNull(Contenido["txtRevistaEditor"]), "", CStr(Contenido["txtRevistaEditor"]))
'     FMain.txtRevistaEditorial.Text = IIf(IsNull(Contenido["txtRevistaEditorial"]), "", CStr(Contenido["txtRevistaEditorial"]))
'     FMain.txtRevistaPais.Text = IIf(IsNull(Contenido["txtRevistaPais"]), "", CStr(Contenido["txtRevistaPais"]))
'     FMain.txtRevistaIdioma.Text = IIf(IsNull(Contenido["txtRevistaIdioma"]), "", CStr(Contenido["txtRevistaIdioma"]))
'     FMain.txtRevistaFrecuencia.Text = IIf(IsNull(Contenido["txtRevistaFrecuencia"]), "", CStr(Contenido["txtRevistaFrecuencia"]))
'     FMain.txtRevistaURL.Text = IIf(IsNull(Contenido["txtRevistaURL"]), "", CStr(Contenido["txtRevistaURL"]))
'     FMain.txtRevistaEmail.Text = IIf(IsNull(Contenido["txtRevistaEmail"]), "", CStr(Contenido["txtRevistaEmail"]))
'     FMain.txtRevistaISSNPrint.Text = IIf(IsNull(Contenido["txtRevistaISSNPrint"]), "", CStr(Contenido["txtRevistaISSNPrint"]))
'     FMain.txtRevistaISSNOnLine.Text = IIf(IsNull(Contenido["txtRevistaISSNOnLine"]), "", CStr(Contenido["txtRevistaISSNOnLine"]))
'     FMain.txtRevistaTipoAcceso.Text = IIf(IsNull(Contenido["txtRevistaTipoAcceso"]), "", CStr(Contenido["txtRevistaTipoAcceso"]))
'     FMain.txtRevistaAreaTematica.Text = IIf(IsNull(Contenido["txtRevistaAreaTematica"]), "", CStr(Contenido["txtRevistaAreaTematica"]))
'     FMain.txtRevistaIndexadaEn.Text = IIf(IsNull(Contenido["txtRevistaIndexadaEn"]), "", CStr(Contenido["txtRevistaIndexadaEn"]))
'     FMain.txtRevistaPoliticaEticaURL.Text = IIf(IsNull(Contenido["txtRevistaPoliticaEticaURL"]), "", CStr(Contenido["txtRevistaPoliticaEticaURL"]))
'     FMain.txtPoliticaRevisoresURL.Text = IIf(IsNull(Contenido["txtPoliticaRevisoresURL"]), "", CStr(Contenido["txtPoliticaRevisoresURL"]))
'     FMain.txtPoliticaOpenAccessURL.Text = IIf(IsNull(Contenido["txtPoliticaOpenAccessURL"]), "", CStr(Contenido["txtPoliticaOpenAccessURL"]))
'     FMain.txtFormatoPublicacion.Text = IIf(IsNull(Contenido["txtFormatoPublicacion"]), "", CStr(Contenido["txtFormatoPublicacion"]))
'     FMain.txtRevistaArchivaEn.Text = IIf(IsNull(Contenido["txtRevistaArchivaEn"]), "", CStr(Contenido["txtRevistaArchivaEn"]))
'     FMain.txtEditorJefe.Text = IIf(IsNull(Contenido["txtEditorJefe"]), "", CStr(Contenido["txtEditorJefe"]))
'     FMain.txtEditorJefeEmail.Text = IIf(IsNull(Contenido["txtEditorJefeEmail"]), "", CStr(Contenido["txtEditorJefeEmail"]))
'     FMain.txtEditorAsociado.Text = IIf(IsNull(Contenido["txtEditorAsociado"]), "", CStr(Contenido["txtEditorAsociado"]))
'     FMain.txtEditorAsociadoEmail.Text = IIf(IsNull(Contenido["txtEditorAsociadoEmail"]), "", CStr(Contenido["txtEditorAsociadoEmail"]))
'     FMain.txtCoordinadorEditorial.Text = IIf(IsNull(Contenido["txtCoordinadorEditorial"]), "", CStr(Contenido["txtCoordinadorEditorial"]))
'     FMain.txtCoordinadorEditorialEmail.Text = IIf(IsNull(Contenido["txtCoordinadorEditorialEmail"]), "", CStr(Contenido["txtCoordinadorEditorialEmail"]))
'     FMain.txtFechaRecepcionApertura.Text = IIf(IsNull(Contenido["txtFechaRecepcionApertura"]), "", CStr(Contenido["txtFechaRecepcionApertura"]))
'     FMain.txtFechaRecepcionCierre.Text = IIf(IsNull(Contenido["txtFechaRecepcionCierre"]), "", CStr(Contenido["txtFechaRecepcionCierre"]))
'     FMain.txtFechaPublicacion.Text = IIf(IsNull(Contenido["txtFechaPublicacion"]), "", CStr(Contenido["txtFechaPublicacion"]))
'     FMain.txtFechaProximaEdicion.Text = IIf(IsNull(Contenido["txtFechaProximaEdicion"]), "", CStr(Contenido["txtFechaProximaEdicion"]))
'     FMain.txtLicencia.Text = IIf(IsNull(Contenido["txtLicencia"]), "", CStr(Contenido["txtLicencia"]))
'     FMain.txtDerechosAutor.Text = IIf(IsNull(Contenido["txtDerechosAutor"]), "", CStr(Contenido["txtDerechosAutor"]))
'     FMain.txtDepositarioLegal.Text = IIf(IsNull(Contenido["txtDepositarioLegal"]), "", CStr(Contenido["txtDepositarioLegal"]))
'     FMain.cmbTipoCSL.Text = IIf(IsNull(Contenido["cmbTipoCSL"]), "", CStr(Contenido["cmbTipoCSL"]))
'     FMain.txtLibroResumenEs.Text = IIf(IsNull(Contenido["txtLibroResumenEs"]), "", CStr(Contenido["txtLibroResumenEs"]))
'     FMain.txtLibroPalabrasClaveEs.Text = IIf(IsNull(Contenido["txtLibroPalabrasClaveEs"]), "", CStr(Contenido["txtLibroPalabrasClaveEs"]))
'     FMain.txtLibroResumenEn.Text = IIf(IsNull(Contenido["txtLibroResumenEn"]), "", CStr(Contenido["txtLibroResumenEn"]))
'     FMain.txtLibroPalabrasClaveEn.Text = IIf(IsNull(Contenido["txtLibroPalabrasClaveEn"]), "", CStr(Contenido["txtLibroPalabrasClaveEn"]))
'     FMain.cmbAutoriaLibro.Index = Contenido["cmbAutoriaLibro"]
'     FMain.txtLibroAutoria.Text = IIf(IsNull(Contenido["txtLibroAutoria"]), "", CStr(Contenido["txtLibroAutoria"]))
'     FMain.txtLibroSerie.Text = IIf(IsNull(Contenido["txtLibroSerie"]), "", CStr(Contenido["txtLibroSerie"]))
'     FMain.txtLibroSerieNumero.Text = IIf(IsNull(Contenido["txtLibroSerieNumero"]), "", CStr(Contenido["txtLibroSerieNumero"]))
'     FMain.txtLibroGenero.Text = IIf(IsNull(Contenido["txtLibroGenero"]), "", CStr(Contenido["txtLibroGenero"]))
'     FMain.txtLibroAudiencia.Text = IIf(IsNull(Contenido["txtLibroAudiencia"]), "", CStr(Contenido["txtLibroAudiencia"]))
'     FMain.txtLibroSubtitulo.Text = IIf(IsNull(Contenido["txtLibroSubtitulo"]), "", CStr(Contenido["txtLibroSubtitulo"]))
'     FMain.txtLogoCabecera.Text = IIf(IsNull(Contenido["txtLogoCabecera"]), "", CStr(Contenido["txtLogoCabecera"]))
'     FMain.txtGhpFooter.Text = IIf(IsNull(Contenido["txtGhpFooter"]), "", Contenido["txtGhpFooter"])
'     FMain.txtGoogleAnalytics.Text = IIf(IsNull(Contenido["txtGoogleAnalytics"]), "", CStr(Contenido["txtGoogleAnalytics"]))
'     FMain.txtDescarga.Text = IIf(IsNull(Contenido["txtDescarga"]), "", CStr(Contenido["txtDescarga"]))
'     FMain.txtRevistaDoi.Text = IIf(IsNull(Contenido["txtRevistaDoi"]), "", CStr(Contenido["txtRevistaDoi"]))
'     FMain.txtRevistaPURL.Text = IIf(IsNull(Contenido["txtRevistaPURL"]), "", CStr(Contenido["txtRevistaPURL"]))
'     FMain.txtRevistaCDL.Text = IIf(IsNull(Contenido["txtRevistaCDL"]), "", CStr(Contenido["txtRevistaCDL"]))
'     FMain.txtLibroRepositorioGithub.Text = IIf(IsNull(Contenido["txtLibroRepositorioGithub"]), "", CStr(Contenido["txtLibroRepositorioGithub"]))
'   Endif
'   ' Si llegamos aquí, todo salió bien
'   Return True
'
' Catch
'   m_Sonido.sonar("Error")
'   Message.Error("Error al cargar metadatos: " & Error.Text)
'   Return False
'
' End
'
' Public Sub LimpiarCamposMetadatos()
'
'   FMain.txtImagenTapita.Text = ""
'   FMain.txtRevistaTitulo.Text = ""
'   FMain.txtRevistaAbreviatura.Text = ""
'   FMain.txtRevistaDOIPrefix.Text = ""
'   FMain.txtRevistaISSN.Text = ""
'   FMain.txtRevistaVolumen.Text = ""
'   FMain.txtRevistaNumero.Text = ""
'   FMain.txtRevistaAnio.Text = ""
'   FMain.txtRevistaMes.Text = ""
'   FMain.txtRevistaEditor.Text = ""
'   FMain.txtRevistaEditorial.Text = ""
'   FMain.txtRevistaPais.Text = ""
'   FMain.txtRevistaIdioma.Text = ""
'   FMain.txtRevistaFrecuencia.Text = ""
'   FMain.txtRevistaURL.Text = ""
'   FMain.txtRevistaEmail.Text = ""
'   FMain.txtRevistaISSNPrint.Text = ""
'   FMain.txtRevistaISSNOnLine.Text = ""
'   FMain.txtRevistaTipoAcceso.Text = ""
'   FMain.txtRevistaAreaTematica.Text = ""
'   FMain.txtRevistaIndexadaEn.Text = ""
'   FMain.txtRevistaPoliticaEticaURL.Text = ""
'   FMain.txtPoliticaRevisoresURL.Text = ""
'   FMain.txtPoliticaOpenAccessURL.Text = ""
'   FMain.txtFormatoPublicacion.Text = ""
'   FMain.txtRevistaArchivaEn.Text = ""
'   FMain.txtEditorJefe.Text = ""
'   FMain.txtEditorJefeEmail.Text = ""
'   FMain.txtEditorAsociado.Text = ""
'   FMain.txtEditorAsociadoEmail.Text = ""
'   FMain.txtCoordinadorEditorial.Text = ""
'   FMain.txtCoordinadorEditorialEmail.Text = ""
'   FMain.txtFechaRecepcionApertura.Text = ""
'   FMain.txtFechaRecepcionCierre.Text = ""
'   FMain.txtFechaPublicacion.Text = ""
'   FMain.txtFechaProximaEdicion.Text = ""
'   FMain.txtLicencia.Text = ""
'   FMain.txtDerechosAutor.Text = ""
'   FMain.txtDepositarioLegal.Text = ""
'   FMain.cmbTipoCSL.Text = ""
'   FMain.tipo_producto.Text = ""
'   FMain.txtLibroResumenEs.Text = ""
'   FMain.txtLibroPalabrasClaveEs.Text = ""
'   FMain.txtLibroResumenEn.Text = ""
'   FMain.txtLibroPalabrasClaveEn.Text = ""
'   FMain.txtLibroAutoria.Text = ""
'   FMain.txtLibroSerie.Text = ""
'   FMain.txtLibroSerieNumero.Text = ""
'   FMain.txtLibroGenero.Text = ""
'   FMain.txtLibroAudiencia.Text = ""
'   FMain.txtLibroSubtitulo.Text = ""
'   FMain.txtLogoCabecera.Text = ""
'   FMain.txtGhpFooter.Text = ""
'   FMain.txtGoogleAnalytics.Text = ""
'   FMain.txtDescarga.Text = ""
'   FMain.txtRevistaDoi.Text = ""
'   FMain.txtRevistaPURL.Text = ""
'   FMain.txtRevistaCDL.Text = ""
'   FMain.txtLibroRepositorioGithub.Text = ""
'
' End

' Public Sub GuardarMetadatos()
'
'   ContenidoMeta = m_ConexionBD.mConn.Edit("metadatos", "id=" & FMain.id_proyecto.Value)
'
'   Contenido!txtImagenTapita = FMain.txtImagenTapita.Text
'   Contenido!txtRevistaTitulo = FMain.txtRevistaTitulo.Text
'   Contenido!txtRevistaAbreviatura = FMain.txtRevistaAbreviatura.Text
'   Contenido!txtRevistaDOIPrefix = FMain.txtRevistaDOIPrefix.Text
'   Contenido!txtRevistaISSN = FMain.txtRevistaISSN.Text
'   Contenido!txtRevistaVolumen = FMain.txtRevistaVolumen.Text
'   Contenido!txtRevistaNumero = FMain.txtRevistaNumero.Text
'   Contenido!txtRevistaAnio = FMain.txtRevistaAnio.Text
'   Contenido!txtRevistaMes = FMain.txtRevistaMes.Text
'   Contenido!txtRevistaEditor = FMain.txtRevistaEditor.Text
'   Contenido!txtRevistaEditorial = FMain.txtRevistaEditorial.Text
'   Contenido!txtRevistaPais = FMain.txtRevistaPais.Text
'   Contenido!txtRevistaIdioma = FMain.txtRevistaIdioma.Text
'   Contenido!txtRevistaFrecuencia = FMain.txtRevistaFrecuencia.Text
'   Contenido!txtRevistaURL = FMain.txtRevistaURL.Text
'   Contenido!txtRevistaEmail = FMain.txtRevistaEmail.Text
'   Contenido!txtRevistaISSNPrint = FMain.txtRevistaISSNPrint.Text
'   Contenido!txtRevistaISSNOnLine = FMain.txtRevistaISSNOnLine.Text
'   Contenido!txtRevistaTipoAcceso = FMain.txtRevistaTipoAcceso.Text
'   Contenido!txtRevistaAreaTematica = FMain.txtRevistaAreaTematica.Text
'   Contenido!txtRevistaIndexadaEn = FMain.txtRevistaIndexadaEn.Text
'   Contenido!txtRevistaPoliticaEticaURL = FMain.txtRevistaPoliticaEticaURL.Text
'   Contenido!txtPoliticaRevisoresURL = FMain.txtPoliticaRevisoresURL.Text
'   Contenido!txtPoliticaOpenAccessURL = FMain.txtPoliticaOpenAccessURL.Text
'   Contenido!txtFormatoPublicacion = FMain.txtFormatoPublicacion.Text
'   Contenido!txtRevistaArchivaEn = FMain.txtRevistaArchivaEn.Text
'   Contenido!txtEditorJefe = FMain.txtEditorJefe.Text
'   Contenido!txtEditorJefeEmail = FMain.txtEditorJefeEmail.Text
'   Contenido!txtEditorAsociado = FMain.txtEditorAsociado.Text
'   Contenido!txtEditorAsociadoEmail = FMain.txtEditorAsociadoEmail.Text
'   Contenido!txtCoordinadorEditorial = FMain.txtCoordinadorEditorial.Text
'   Contenido!txtCoordinadorEditorialEmail = FMain.txtCoordinadorEditorialEmail.Text
'   Contenido!txtFechaRecepcionApertura = FMain.txtFechaRecepcionApertura.Text
'   Contenido!txtFechaRecepcionCierre = FMain.txtFechaRecepcionCierre.Text
'   Contenido!txtFechaPublicacion = FMain.txtFechaPublicacion.Text
'   Contenido!txtFechaProximaEdicion = FMain.txtFechaProximaEdicion.Text
'   Contenido!txtLicencia = FMain.txtLicencia.Text
'   Contenido!txtDerechosAutor = FMain.txtDerechosAutor.Text
'   Contenido!txtDepositarioLegal = FMain.txtDepositarioLegal.Text
'   Contenido!cmbTipoCSL = FMain.cmbTipoCSL.Text
'   Contenido!tipo_producto = FMain.tipo_producto.Text
'   Contenido!txtLibroResumenEs = FMain.txtLibroResumenEs.Text
'   Contenido!txtLibroPalabrasClaveEs = FMain.txtLibroPalabrasClaveEs.Text
'   Contenido!txtLibroResumenEn = FMain.txtLibroResumenEn.Text
'   Contenido!txtLibroPalabrasClaveEn = FMain.txtLibroPalabrasClaveEn.Text
'   Contenido!cmbAutoriaLibro = FMain.cmbAutoriaLibro.Index
'   Contenido!txtLibroAutoria = FMain.txtLibroAutoria.Text
'   Contenido!txtLibroSerie = FMain.txtLibroSerie.Text
'   Contenido!txtLibroSerieNumero = FMain.txtLibroSerieNumero.Text
'   Contenido!txtLibroGenero = FMain.txtLibroGenero.Text
'   Contenido!txtLibroAudiencia = FMain.txtLibroAudiencia.Text
'   Contenido!txtLibroSubtitulo = FMain.txtLibroSubtitulo.Text
'   Contenido!txtLogoCabecera = FMain.txtLogoCabecera.Text
'   Contenido!txtGhpFooter = FMain.txtGhpFooter.Text
'   Contenido!txtGoogleAnalytics = FMain.txtGoogleAnalytics.Text
'   Contenido!txtDescarga = FMain.txtDescarga.Text
'   Contenido!txtRevistaDoi = FMain.txtRevistaDoi.Text
'   Contenido!txtRevistaPURL = FMain.txtRevistaPURL.Text
'   Contenido!txtRevistaCDL = FMain.txtRevistaCDL.Text
'   Contenido!txtLibroRepositorioGithub = FMain.txtLibroRepositorioGithub.Text
'
'   Contenido.Update
'   m_ConexionBD.mConn.Commit()
'   m_Sonido.sonar("Info")
'   Message.Info("Cambios guardados correctamente.")
'
' Catch
'   m_Sonido.sonar("Error")
'   Message.Error("Error al guardar cambios: " & Error.Text)
'
' End

' Public Sub BuscarMetadatoPorCampo(campo As TextBox, grid As GridView)
'
'   Dim sCampoBD As String = campo.Name
'   Dim sValor As String = Trim(campo.Text)
'
'   Dim sConsulta As String
'
'   If sValor = "" Then
'     m_Sonido.sonar("Warning")
'     Message.Warning("Debe introducir contenido a buscar.")
'     campo.SetFocus
'     Return
'   Endif
'
'   sConsulta = "SELECT * FROM proyectos WHERE " & sCampoBD & " LIKE '%" & sValor & "%' ORDER BY id DESC;"
'   CargarDatosResultados(sConsulta, grid)
'
' End

' Public Sub CargarDatosResultados(sConsulta As String, Grid As GridView)
'
'   Dim i As Integer
'   Dim j As Integer
'
'   ' Ejecutar la consulta
'   Contenido = m_ConexionBD.mConn.Exec(sConsulta)
'
'   ' Si no hay resultados
'   If Contenido.Count = 0 Then
'     m_Sonido.sonar("Info")
'     Message.Info("No se ha encontrado ningún resultado.")
'     Return
'   Endif
'
'   ' Limpiar el Grid antes de mostrar los resultados
'   Grid.Clear()
'   Grid.Rows.Count = Contenido.Count
'
'   ' Llenar el Grid con los resultados
'   For i = 0 To Contenido.Count - 1
'     For j = 0 To Contenido.Fields.Count - 1
'       Try Grid[i, j].Text = Contenido[j]
'       If Error Then Grid[i, j].Text = ""
'     Next
'     Contenido.MoveNext
'   Next
'
' End
