' Gambas module file

Private MiSonido As Sound
Private rutaSonido As String = User.Home &/ ".gbpublisher/sonido"

Public Sub sonar(cancion As String)

  Select Case cancion
    Case "Error"
      Try MiSonido = Sound.Load(rutaSonido &/ "Error.ogg")
    Case "Question"
      Try MiSonido = Sound.Load(rutaSonido &/ "Question.oga")
    Case "Info"
      Try MiSonido = Sound.Load(rutaSonido &/ "Info.ogg")
    Case "OpenApp"
      Try MiSonido = Sound.Load(rutaSonido &/ "OpenApp.ogg")
    Case "Warning"
      Try MiSonido = Sound.Load(rutaSonido &/ "Warning.ogg")
  End Select

  ' Verificamos que MiSonido no sea Null antes de reproducir
  If MiSonido Then
    Try MiSonido.Play()
  Endif

End
