' Gambas module file

' ================================================================
'  Módulo: m_Sonido
'  Propósito:
'     Proveer una interfaz simple para reproducir sonidos del
'     sistema según eventos de la aplicación.
'
'  Descripción:
'     El módulo gestiona la carga y reproducción de sonidos
'     almacenados en la carpeta:
'
'        ~/.gbpublisher/sonido
'
'     Permite reproducir diferentes efectos según una palabra clave
'     (“Error”, “Warning”, “OpenApp”, etc.).
'
'  Dependencias:
'     - Clase Sound (Gambas)
'
' ================================================================

Private MiSonido As Sound
Private rutaSonido As String = User.Home &/ ".gbpublisher/sonido"

Public Sub sonar(cancion As String)

  Select Case cancion
    Case "Error"
      Try MiSonido = Sound.Load(rutaSonido &/ "Error.ogg")
    Case "Question"
      Try MiSonido = Sound.Load(rutaSonido &/ "Question.ogg")
    Case "Info"
      Try MiSonido = Sound.Load(rutaSonido &/ "Info.ogg")
    Case "OpenApp"
      Try MiSonido = Sound.Load(rutaSonido &/ "OpenApp.ogg")
    Case "Warning"
      Try MiSonido = Sound.Load(rutaSonido &/ "Warning.ogg")
  End Select

  ' Verificamos que MiSonido no sea Null antes de reproducir
  If MiSonido Then
    Try MiSonido.Play()
  Endif

End
