' Gambas module file

Private MiSonido As Sound

Public Sub sonar(cancion As String)

  Select Case cancion
    Case "Error"
      Try MiSonido = Sound.Load("Sonido/Error.ogg")
    Case "Question"
      Try MiSonido = Sound.Load("Sonido/Question.oga")
    Case "Info"
      Try MiSonido = Sound.Load("Sonido/Info.ogg")
    Case "OpenApp"
      Try MiSonido = Sound.Load("Sonido/OpenApp.ogg")
    Case "Warning"
      Try MiSonido = Sound.Load("Sonido/Warning.ogg")

  End Select

  Try MiSonido.Play()

End
